pip install peft
pip install torchvision==0.16.0
pip install OmegaConf
pip install iopath
pip install timm
pip install decord
pip install webdataset
pip install pandas
pip install opencv-python
pip install einops
pip install sentencepiece
pip install scikit-learn
pip install imageio
pip install moviepy
pip install scenedetect
pip install pytorchvideo
pip install wandb
pip install accelerate==0.27.2